name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer dépendances système
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk unzip

      - name: Installer Buildozer
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython virtualenv

      - name: Configurer le SDK Android manuellement
        run: |
          mkdir -p ~/.android
          mkdir -p ~/.buildozer/android/platform
          cd ~/.buildozer/android/platform
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip -q cmdtools.zip -d android-sdk
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          # Installation des composants Android (avec acceptation auto des licences)
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;36.1.0"

      - name: Construire l’APK
        run: |
          buildozer android debug
