name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer les dépendances système
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk unzip git

      - name: Installer Buildozer et Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Accepter les licences Android SDK
        run: |
          yes | sdkmanager --licenses || true

      - name: Installer les outils Android requis
        run: |
          yes | sdkmanager --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;36.1.0" || true

      - name: Compiler l’APK
        run: buildozer android debug
